version: '2'

services:
  ebla:
    image: ebla
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 4000:4000
  
  slack_mock:
    image: slack_mock
    build:
      context: test/slack_mock
      dockerfile: Dockerfile
  
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080